package Factories;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 * Created by fabricejeannet on 06/06/2016.
 */
public class XMLFactory {


    public File getFakeFile(String content) throws IOException {
        File fakeFile = new File("fakefile.xml");
        FileWriter fw = new FileWriter(fakeFile);
        fw.write(content);
        fw.close();
        return fakeFile;
    }

    public File competitionInformations() throws IOException {
        final String faxeXML = "<?xml version=\"1.0\" encoding=\"iso-8859-1\" ?>\n" +
                "<!DOCTYPE CompetitionParEquipes>\n" +
                "<!-- Generated by Engarde(Basic) 9.632 - 24/9/2015 -->\n" +
                "<CompetitionParEquipes Championnat=\"FFE\" ID=\"26182\" Annee=\"2015/2016\" Arme=\"S\" Sexe=\"F\" Federation=\"FFE\" Organisateur=\"Thonon\" Categorie=\"C\" Date=\"15.05.2016\" TitreCourt=\"SDC-eq\" TitreLong=\"Championnat de France\" URLorganisateur=\"http://francethononescrimeclub.weebly.com\" >\n" +
                "</CompetitionParEquipes>\n";
        return getFakeFile(faxeXML);
    }

    public File oneTeamCompetition() throws IOException {
        final String faxeXML = "<?xml version=\"1.0\" encoding=\"iso-8859-1\" ?>\n" +
                "<!DOCTYPE CompetitionParEquipes>\n" +
                "<!-- Generated by Engarde(Basic) 9.632 - 24/9/2015 -->\n" +
                "<CompetitionParEquipes Championnat=\"FFE\" ID=\"26182\" Annee=\"2015/2016\" Arme=\"S\" Sexe=\"F\" Federation=\"FFE\" Organisateur=\"Thonon\" Categorie=\"C\" Date=\"15.05.2016\" TitreCourt=\"SDC-eq\" TitreLong=\"Championnat de France\" URLorganisateur=\"http://francethononescrimeclub.weebly.com\" >\n" +
                "  <Equipes>\n" +
                "    <Equipe ID=\"9\" Nom=\"BORDEAUX CAM 1\" Nation=\"FRA\" Ligue=\"AQUITAINE\" Club=\"BORDEAUX CAM\" Classement=\"14\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"29\" Nom=\"CARRE\" Prenom=\"Adele\" DateNaissance=\"12.03.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"AQUITAINE\" Club=\"BORDEAUX CAM\" LicenceNat=\"040640210185\" />\n" +
                "      <Tireur ID=\"30\" Nom=\"TOTO du Bord de-la-plage\" Prenom=\"elsa\" DateNaissance=\"19.05.1999\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"AQUITAINE\" Club=\"BORDEAUX CAM\" LicenceNat=\"040330280268\" />\n" +
                "      <Tireur ID=\"31\" Nom=\"HASNER\" Prenom=\"Alix\" DateNaissance=\"31.03.2000\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"AQUITAINE\" Club=\"BORDEAUX CAM\" LicenceNat=\"040330280407\" />\n" +
                "    </Equipe>\n" +
                "   </Equipes>\n" +
                "</CompetitionParEquipes>\n";
        return getFakeFile(faxeXML);
    }

    public File completeTeamCompetition() throws IOException {
        final String faxeXML = "<?xml version=\"1.0\" encoding=\"iso-8859-1\" ?>\n" +
                "<!DOCTYPE CompetitionParEquipes>\n" +
                "<!-- Generated by Engarde(Basic) 9.632 - 24/9/2015 -->\n" +
                "<CompetitionParEquipes Championnat=\"FFE\" ID=\"26182\" Annee=\"2015/2016\" Arme=\"S\" Sexe=\"F\" Federation=\"FFE\" Organisateur=\"Thonon\" Categorie=\"C\" Date=\"15.05.2016\" TitreCourt=\"SDC-eq\" TitreLong=\"Championnat de France\" URLorganisateur=\"http://francethononescrimeclub.weebly.com\" >\n" +
                "  <Equipes>\n" +
                "    <Equipe ID=\"9\" Nom=\"BORDEAUX CAM 1\" Nation=\"FRA\" Ligue=\"AQUITAINE\" Club=\"BORDEAUX CAM\" Classement=\"14\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"29\" Nom=\"CARRE\" Prenom=\"Adele\" DateNaissance=\"12.03.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"AQUITAINE\" Club=\"BORDEAUX CAM\" LicenceNat=\"040640210185\" />\n" +
                "      <Tireur ID=\"30\" Nom=\"GUENOUN\" Prenom=\"Elsa\" DateNaissance=\"19.05.1999\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"AQUITAINE\" Club=\"BORDEAUX CAM\" LicenceNat=\"040330280268\" />\n" +
                "      <Tireur ID=\"31\" Nom=\"HASNER\" Prenom=\"Alix\" DateNaissance=\"31.03.2000\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"AQUITAINE\" Club=\"BORDEAUX CAM\" LicenceNat=\"040330280407\" />\n" +
                "    </Equipe>\n" +
                "    <Equipe ID=\"17\" Nom=\"CHARLEVILLE 1\" Nation=\"FRA\" Ligue=\"CHAMPAGNE-ARDENNE\" Club=\"CHARLEVILLE\" Classement=\"17\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"59\" Nom=\"BOURGEOIS\" Prenom=\"Alix\" DateNaissance=\"31.08.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"CHAMPAGNE-ARDENNE\" Club=\"CHARLEVILLE\" LicenceNat=\"220080010180\" />\n" +
                "      <Tireur ID=\"58\" Nom=\"HOHMANN\" Prenom=\"Melanie\" DateNaissance=\"07.02.2000\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"CHAMPAGNE-ARDENNE\" Club=\"CHARLEVILLE\" LicenceNat=\"220080030074\" />\n" +
                "      <Tireur ID=\"60\" Nom=\"STEVENIN\" Prenom=\"Noemie\" DateNaissance=\"09.10.2002\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"CHAMPAGNE-ARDENNE\" Club=\"CHARLEVILLE\" LicenceNat=\"220080010463\" />\n" +
                "    </Equipe>\n" +
                "    <Equipe ID=\"5\" Nom=\"CHATOU 1\" Nation=\"FRA\" Ligue=\"ILE DE FRANCE OU\" Club=\"CHATOU\" Classement=\"16\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"16\" Nom=\"GUILLAUME\" Prenom=\"Ines\" DateNaissance=\"27.12.2000\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"ILE DE FRANCE OU\" Club=\"CHATOU\" LicenceNat=\"280780850380\" />\n" +
                "      <Tireur ID=\"14\" Nom=\"QUERLEU\" Prenom=\"Daphne\" DateNaissance=\"09.08.2000\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"ILE DE FRANCE OU\" Club=\"CHATOU\" LicenceNat=\"280780850242\" />\n" +
                "      <Tireur ID=\"15\" Nom=\"SALHI\" Prenom=\"Ines\" DateNaissance=\"06.01.2000\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"ILE DE FRANCE OU\" Club=\"CHATOU\" LicenceNat=\"280780850342\" />\n" +
                "    </Equipe>\n" +
                "    <Equipe ID=\"8\" Nom=\"DINARD LAMES 1\" Nation=\"FRA\" Ligue=\"BRETAGNE\" Club=\"DINARD LAMES\" Classement=\"10\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"25\" Nom=\"BONGRE\" Prenom=\"Daphne\" DateNaissance=\"17.12.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"BRETAGNE\" Club=\"DINARD LAMES\" LicenceNat=\"230350330092\" />\n" +
                "      <Tireur ID=\"27\" Nom=\"BOUREL\" Prenom=\"Marie\" DateNaissance=\"11.06.2002\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"BRETAGNE\" Club=\"DINARD LAMES\" LicenceNat=\"230350330204\" />\n" +
                "      <Tireur ID=\"28\" Nom=\"LASBLEIZ\" Prenom=\"Anna\" DateNaissance=\"04.08.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"BRETAGNE\" Club=\"DINARD LAMES\" LicenceNat=\"230350330132\" />\n" +
                "      <Tireur ID=\"26\" Nom=\"THIEBAUT\" Prenom=\"Margaux\" DateNaissance=\"17.10.1999\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"BRETAGNE\" Club=\"DINARD LAMES\" LicenceNat=\"230350330165\" />\n" +
                "    </Equipe>\n" +
                "    <Equipe ID=\"11\" Nom=\"GEMENOS 1\" Nation=\"FRA\" Ligue=\"PROVENCE\" Club=\"GEMENOS\" Classement=\"3\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"38\" Nom=\"KLEIN\" Prenom=\"Louise\" DateNaissance=\"12.08.2000\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"PROVENCE\" Club=\"GEMENOS\" LicenceNat=\"010130060139\" />\n" +
                "      <Tireur ID=\"39\" Nom=\"PERRIER\" Prenom=\"Eleonore\" DateNaissance=\"10.12.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"PROVENCE\" Club=\"GEMENOS\" LicenceNat=\"010130060148\" />\n" +
                "      <Tireur ID=\"36\" Nom=\"POUPINET\" Prenom=\"Anne\" DateNaissance=\"27.04.2000\" Sexe=\"F\" Lateralite=\"G\" Nation=\"FRA\" Ligue=\"PROVENCE\" Club=\"GEMENOS\" LicenceNat=\"010130060120\" />\n" +
                "      <Tireur ID=\"37\" Nom=\"SUZANNE\" Prenom=\"Coline\" DateNaissance=\"30.01.1999\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"PROVENCE\" Club=\"GEMENOS\" LicenceNat=\"010130060117\" />\n" +
                "    </Equipe>\n" +
                "    <Equipe ID=\"6\" Nom=\"GISORS 3A 1\" Nation=\"FRA\" Ligue=\"HAUTE-NORMANDIE\" Club=\"GISORS 3A\" Classement=\"15\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"17\" Nom=\"BOULAY\" Prenom=\"Anais\" DateNaissance=\"20.01.1999\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"HAUTE-NORMANDIE\" Club=\"GISORS 3A\" LicenceNat=\"110270040142\" />\n" +
                "      <Tireur ID=\"19\" Nom=\"LAKRI\" Prenom=\"Kenza\" DateNaissance=\"16.09.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"HAUTE-NORMANDIE\" Club=\"GISORS 3A\" LicenceNat=\"110270040208\" />\n" +
                "      <Tireur ID=\"20\" Nom=\"LE VILAIN\" Prenom=\"Audrey\" DateNaissance=\"30.06.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"HAUTE-NORMANDIE\" Club=\"GISORS 3A\" LicenceNat=\"110270040322\" />\n" +
                "      <Tireur ID=\"18\" Nom=\"PHILIPPE LEROY\" Prenom=\"Rebecca\" DateNaissance=\"10.05.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"HAUTE-NORMANDIE\" Club=\"GISORS 3A\" LicenceNat=\"110270040251\" />\n" +
                "    </Equipe>\n" +
                "    <Equipe ID=\"1\" Nom=\"MAISONS ALF 1\" Nation=\"FRA\" Ligue=\"CRETEIL\" Club=\"MAISONS ALF\" Classement=\"1\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"1\" Nom=\"ALLIETTA\" Prenom=\"Clemence\" DateNaissance=\"31.03.2002\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"CRETEIL\" Club=\"MAISONS ALF\" LicenceNat=\"260941880132\" />\n" +
                "      <Tireur ID=\"2\" Nom=\"COUDERC\" Prenom=\"Annah\" DateNaissance=\"22.01.2002\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"CRETEIL\" Club=\"MAISONS ALF\" LicenceNat=\"260941880162\" />\n" +
                "      <Tireur ID=\"3\" Nom=\"HENRION\" Prenom=\"Garance\" DateNaissance=\"07.06.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"CRETEIL\" Club=\"MAISONS ALF\" LicenceNat=\"260941880188\" />\n" +
                "      <Tireur ID=\"4\" Nom=\"PALLOT\" Prenom=\"Rachel\" DateNaissance=\"12.01.1999\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"CRETEIL\" Club=\"MAISONS ALF\" LicenceNat=\"260941880236\" />\n" +
                "    </Equipe>\n" +
                "    <Equipe ID=\"12\" Nom=\"MEYLAN SE 1\" Nation=\"FRA\" Ligue=\"DAUPHINE-SAVOIE\" Club=\"MEYLAN SE\" Classement=\"5\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"61\" Nom=\"DOUCET\" Prenom=\"Mathilde\" DateNaissance=\"15.01.2000\" Sexe=\"F\" Lateralite=\"I\" Nation=\"FRA\" Ligue=\"DAUPHINE-SAVOIE\" Club=\"MEYLAN SE\" LicenceNat=\"080380120246\" />\n" +
                "      <Tireur ID=\"40\" Nom=\"FERAUD\" Prenom=\"Sarah\" DateNaissance=\"13.06.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"DAUPHINE-SAVOIE\" Club=\"MEYLAN SE\" LicenceNat=\"080380120258\" />\n" +
                "      <Tireur ID=\"41\" Nom=\"KOWALSKI\" Prenom=\"Katia\" DateNaissance=\"14.03.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"DAUPHINE-SAVOIE\" Club=\"MEYLAN SE\" LicenceNat=\"080380120283\" />\n" +
                "      <Tireur ID=\"42\" Nom=\"LEBEL\" Prenom=\"Ariane\" DateNaissance=\"19.01.2000\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"DAUPHINE-SAVOIE\" Club=\"MEYLAN SE\" LicenceNat=\"080380120409\" />\n" +
                "    </Equipe>\n" +
                "    <Equipe ID=\"7\" Nom=\"ORLEANS CE 1\" Nation=\"FRA\" Ligue=\"CENTRE\" Club=\"ORLEANS CE\" Classement=\"6\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"23\" Nom=\"CLAPIER\" Prenom=\"Faustine\" DateNaissance=\"06.12.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"CENTRE\" Club=\"ORLEANS CE\" LicenceNat=\"200450230398\" />\n" +
                "      <Tireur ID=\"24\" Nom=\"FONDEUR\" Prenom=\"Apolline\" DateNaissance=\"27.07.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"CENTRE\" Club=\"ORLEANS CE\" LicenceNat=\"200450230455\" />\n" +
                "      <Tireur ID=\"21\" Nom=\"GALIFRET\" Prenom=\"Mathilde\" DateNaissance=\"23.04.1999\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"CENTRE\" Club=\"ORLEANS CE\" LicenceNat=\"200450230461\" />\n" +
                "      <Tireur ID=\"22\" Nom=\"MARTISKA\" Prenom=\"Aolani\" DateNaissance=\"14.05.1999\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"CENTRE\" Club=\"ORLEANS CE\" LicenceNat=\"200450230532\" />\n" +
                "    </Equipe>\n" +
                "    <Equipe ID=\"4\" Nom=\"PARIS RCF 1\" Nation=\"FRA\" Ligue=\"PARIS\" Club=\"PARIS RCF\" Classement=\"7\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"11\" Nom=\"BARBIER\" Prenom=\"Louise\" DateNaissance=\"26.07.2000\" Sexe=\"F\" Lateralite=\"G\" Nation=\"FRA\" Ligue=\"PARIS\" Club=\"PARIS RCF\" LicenceNat=\"270750471154\" />\n" +
                "      <Tireur ID=\"13\" Nom=\"BERTHIER\" Prenom=\"Noemie\" DateNaissance=\"19.09.2000\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"PARIS\" Club=\"PARIS RCF\" LicenceNat=\"270750471008\" />\n" +
                "      <Tireur ID=\"12\" Nom=\"CONSCIENCE\" Prenom=\"Pauline\" DateNaissance=\"21.07.1999\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"PARIS\" Club=\"PARIS RCF\" LicenceNat=\"270750470617\" />\n" +
                "    </Equipe>\n" +
                "    <Equipe ID=\"2\" Nom=\"PARIS UC 1\" Nation=\"FRA\" Ligue=\"PARIS\" Club=\"PARIS UC\" Classement=\"2\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"5\" Nom=\"GLEIZAL\" Prenom=\"Coline\" DateNaissance=\"12.08.2000\" Sexe=\"F\" Lateralite=\"G\" Nation=\"FRA\" Ligue=\"PARIS\" Club=\"PARIS UC\" LicenceNat=\"270750460535\" />\n" +
                "      <Tireur ID=\"6\" Nom=\"LUSINIER\" Prenom=\"Kelly\" DateNaissance=\"22.07.2000\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"PARIS\" Club=\"PARIS UC\" LicenceNat=\"270750461082\" />\n" +
                "      <Tireur ID=\"7\" Nom=\"MONJOUX\" Prenom=\"Caroline\" DateNaissance=\"21.03.1999\" Sexe=\"F\" Lateralite=\"G\" Nation=\"FRA\" Ligue=\"PARIS\" Club=\"PARIS UC\" LicenceNat=\"270750461058\" />\n" +
                "    </Equipe>\n" +
                "    <Equipe ID=\"3\" Nom=\"PARIS UC 2\" Nation=\"FRA\" Ligue=\"PARIS\" Club=\"PARIS UC\" Classement=\"11\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"8\" Nom=\"ALBRECHT\" Prenom=\"Anne\" DateNaissance=\"26.07.2000\" Sexe=\"F\" Lateralite=\"G\" Nation=\"FRA\" Ligue=\"PARIS\" Club=\"PARIS UC\" LicenceNat=\"270750461083\" />\n" +
                "      <Tireur ID=\"9\" Nom=\"BELKHODJA\" Prenom=\"Mona\" DateNaissance=\"01.06.2000\" Sexe=\"F\" Lateralite=\"G\" Nation=\"FRA\" Ligue=\"PARIS\" Club=\"PARIS UC\" LicenceNat=\"270750461100\" />\n" +
                "      <Tireur ID=\"10\" Nom=\"DIANTEILL\" Prenom=\"Nina\" DateNaissance=\"21.04.2000\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"PARIS\" Club=\"PARIS UC\" LicenceNat=\"270750460496\" />\n" +
                "    </Equipe>\n" +
                "    <Equipe ID=\"14\" Nom=\"PONTARLIER 1\" Nation=\"FRA\" Ligue=\"FRANCHE-COMTE\" Club=\"PONTARLIER\" Classement=\"13\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"48\" Nom=\"MAINTIER\" Prenom=\"Sarah\" DateNaissance=\"11.01.1999\" Sexe=\"F\" Lateralite=\"G\" Nation=\"FRA\" Ligue=\"FRANCHE-COMTE\" Club=\"PONTARLIER\" LicenceNat=\"030250060215\" />\n" +
                "      <Tireur ID=\"50\" Nom=\"REY\" Prenom=\"Naïma\" DateNaissance=\"13.09.1999\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"FRANCHE-COMTE\" Club=\"PONTARLIER\" LicenceNat=\"030250060189\" />\n" +
                "      <Tireur ID=\"49\" Nom=\"ROLET\" Prenom=\"Ninon\" DateNaissance=\"10.03.1999\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"FRANCHE-COMTE\" Club=\"PONTARLIER\" LicenceNat=\"030390160034\" />\n" +
                "    </Equipe>\n" +
                "    <Equipe ID=\"15\" Nom=\"ROUBAIX CE 1\" Nation=\"FRA\" Ligue=\"NORD-PAS DE CALAIS\" Club=\"ROUBAIX CE\" Classement=\"9\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"51\" Nom=\"DEBLECKER\" Prenom=\"Nelly\" DateNaissance=\"23.08.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"NORD-PAS DE CALAIS\" Club=\"ROUBAIX CE\" LicenceNat=\"130590100154\" />\n" +
                "      <Tireur ID=\"53\" Nom=\"LOBBENS\" Prenom=\"Victorine\" DateNaissance=\"19.03.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"NORD-PAS DE CALAIS\" Club=\"ROUBAIX CE\" LicenceNat=\"130590100364\" />\n" +
                "      <Tireur ID=\"52\" Nom=\"VULETIC\" Prenom=\"Ornella\" DateNaissance=\"17.05.2002\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"NORD-PAS DE CALAIS\" Club=\"ROUBAIX CE\" LicenceNat=\"130590100325\" />\n" +
                "    </Equipe>\n" +
                "    <Equipe ID=\"10\" Nom=\"TARBES ATE 1\" Nation=\"FRA\" Ligue=\"MIDI-PYRENEES\" Club=\"TARBES ATE\" Classement=\"8\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"35\" Nom=\"ANCLADES\" Prenom=\"Maylis\" DateNaissance=\"08.10.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"MIDI-PYRENEES\" Club=\"TARBES ATE\" LicenceNat=\"250650200451\" />\n" +
                "      <Tireur ID=\"32\" Nom=\"CANDALOT\" Prenom=\"Lena\" DateNaissance=\"07.01.2000\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"MIDI-PYRENEES\" Club=\"TARBES ATE\" LicenceNat=\"250650200448\" />\n" +
                "      <Tireur ID=\"33\" Nom=\"LAPORTE\" Prenom=\"Anna\" DateNaissance=\"31.05.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"MIDI-PYRENEES\" Club=\"TARBES ATE\" LicenceNat=\"250650200246\" />\n" +
                "      <Tireur ID=\"34\" Nom=\"TOURNEFIER\" Prenom=\"Andrea\" DateNaissance=\"17.04.2002\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"MIDI-PYRENEES\" Club=\"TARBES ATE\" LicenceNat=\"250650200449\" />\n" +
                "    </Equipe>\n" +
                "    <Equipe ID=\"13\" Nom=\"THONON 1\" Nation=\"FRA\" Ligue=\"DAUPHINE-SAVOIE\" Club=\"THONON\" Classement=\"3\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"44\" Nom=\"BOURON\" Prenom=\"Sarah\" DateNaissance=\"09.06.1999\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"DAUPHINE-SAVOIE\" Club=\"THONON\" LicenceNat=\"080740070023\" />\n" +
                "      <Tireur ID=\"45\" Nom=\"JAMET\" Prenom=\"Lucie\" DateNaissance=\"05.01.1999\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"DAUPHINE-SAVOIE\" Club=\"THONON\" LicenceNat=\"080740070075\" />\n" +
                "      <Tireur ID=\"46\" Nom=\"LACROIX\" Prenom=\"Mathilde\" DateNaissance=\"31.03.2000\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"DAUPHINE-SAVOIE\" Club=\"THONON\" LicenceNat=\"080740070077\" />\n" +
                "      <Tireur ID=\"47\" Nom=\"PELET\" Prenom=\"Luna\" DateNaissance=\"24.12.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"DAUPHINE-SAVOIE\" Club=\"THONON\" LicenceNat=\"080740080033\" />\n" +
                "    </Equipe>\n" +
                "    <Equipe ID=\"16\" Nom=\"WATTRELOS CE 1\" Nation=\"FRA\" Ligue=\"NORD-PAS DE CALAIS\" Club=\"WATTRELOS CE\" Classement=\"12\" Statut=\"N\" >\n" +
                "      <Tireur ID=\"54\" Nom=\"BERIEL RODRIGUEZ\" Prenom=\"Claire\" DateNaissance=\"21.05.1999\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"NORD-PAS DE CALAIS\" Club=\"WATTRELOS CE\" LicenceNat=\"130590270070\" />\n" +
                "      <Tireur ID=\"55\" Nom=\"DUPUICH\" Prenom=\"Louise\" DateNaissance=\"11.07.2000\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"NORD-PAS DE CALAIS\" Club=\"WATTRELOS CE\" LicenceNat=\"130590270091\" />\n" +
                "      <Tireur ID=\"57\" Nom=\"GUNIA-LOQUET\" Prenom=\"Natasha\" DateNaissance=\"28.04.2001\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"NORD-PAS DE CALAIS\" Club=\"WATTRELOS CE\" LicenceNat=\"130590270191\" />\n" +
                "      <Tireur ID=\"56\" Nom=\"LEBLON\" Prenom=\"Clemence\" DateNaissance=\"31.01.2000\" Sexe=\"F\" Lateralite=\"D\" Nation=\"FRA\" Ligue=\"NORD-PAS DE CALAIS\" Club=\"WATTRELOS CE\" LicenceNat=\"130590240261\" />\n" +
                "    </Equipe>\n" +
                "  </Equipes>\n" +
                "  <Arbitres>\n" +
                "  </Arbitres>\n" +
                "  <!--    Generated by Engarde(Basic) 9.632 - 24/9/2015    -->\n" +
                "  <Phases>\n" +
                "    <PhaseDeTableaux PhaseID=\"PhaseTableaux1\" ID=\"1\" >\n" +
                "      <Equipe REF=\"9\" RangInitial=\"14\" RangFinal=\"14\" Statut=\"N\" />\n" +
                "      <Equipe REF=\"17\" RangInitial=\"16\" RangFinal=\"17\" Statut=\"N\" />\n" +
                "      <Equipe REF=\"5\" RangInitial=\"17\" RangFinal=\"16\" Statut=\"N\" />\n" +
                "      <Equipe REF=\"8\" RangInitial=\"11\" RangFinal=\"10\" Statut=\"N\" />\n" +
                "      <Equipe REF=\"11\" RangInitial=\"1\" RangFinal=\"3\" Statut=\"N\" />\n" +
                "      <Equipe REF=\"6\" RangInitial=\"15\" RangFinal=\"15\" Statut=\"N\" />\n" +
                "      <Equipe REF=\"1\" RangInitial=\"6\" RangFinal=\"1\" Statut=\"N\" />\n" +
                "      <Equipe REF=\"12\" RangInitial=\"3\" RangFinal=\"5\" Statut=\"N\" />\n" +
                "      <Equipe REF=\"7\" RangInitial=\"5\" RangFinal=\"6\" Statut=\"N\" />\n" +
                "      <Equipe REF=\"4\" RangInitial=\"8\" RangFinal=\"7\" Statut=\"N\" />\n" +
                "      <Equipe REF=\"2\" RangInitial=\"4\" RangFinal=\"2\" Statut=\"N\" />\n" +
                "      <Equipe REF=\"3\" RangInitial=\"9\" RangFinal=\"11\" Statut=\"N\" />\n" +
                "      <Equipe REF=\"14\" RangInitial=\"13\" RangFinal=\"13\" Statut=\"N\" />\n" +
                "      <Equipe REF=\"15\" RangInitial=\"7\" RangFinal=\"9\" Statut=\"N\" />\n" +
                "      <Equipe REF=\"10\" RangInitial=\"10\" RangFinal=\"8\" Statut=\"N\" />\n" +
                "      <Equipe REF=\"13\" RangInitial=\"2\" RangFinal=\"3\" Statut=\"N\" />\n" +
                "      <Equipe REF=\"16\" RangInitial=\"12\" RangFinal=\"12\" Statut=\"N\" />\n" +
                "      <SuiteDeTableaux ID=\"SuiteTab_a\" Titre=\"Tableau de de base\" NbDeTableaux=\"1\" DestinationDesQualifies=\"SuiteTab_B\" >\n" +
                "        <Tableau ID=\"A32\" Titre=\"Tableau de 32\" Taille=\"32\" DestinationDesElimines=\"SuiteTab_C\" >\n" +
                "          <Match ID=\"1\" >\n" +
                "            <Equipe REF=\"11\" Score=\"0\" Statut=\"V\" Place=\"1\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"32\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"2\" >\n" +
                "            <Equipe REF=\"5\" Score=\"45\" Statut=\"V\" Place=\"17\" />\n" +
                "            <Equipe REF=\"17\" Score=\"37\" Statut=\"D\" Place=\"16\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"3\" >\n" +
                "            <Equipe REF=\"3\" Score=\"0\" Statut=\"V\" Place=\"9\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"24\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"4\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"25\" />\n" +
                "            <Equipe REF=\"4\" Score=\"0\" Statut=\"V\" Place=\"8\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"5\" >\n" +
                "            <Equipe REF=\"7\" Score=\"0\" Statut=\"V\" Place=\"5\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"28\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"6\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"21\" />\n" +
                "            <Equipe REF=\"16\" Score=\"0\" Statut=\"V\" Place=\"12\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"7\" >\n" +
                "            <Equipe REF=\"14\" Score=\"0\" Statut=\"V\" Place=\"13\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"20\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"8\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"29\" />\n" +
                "            <Equipe REF=\"2\" Score=\"0\" Statut=\"V\" Place=\"4\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"9\" >\n" +
                "            <Equipe REF=\"12\" Score=\"0\" Statut=\"V\" Place=\"3\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"30\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"10\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"19\" />\n" +
                "            <Equipe REF=\"9\" Score=\"0\" Statut=\"V\" Place=\"14\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"11\" >\n" +
                "            <Equipe REF=\"8\" Score=\"0\" Statut=\"V\" Place=\"11\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"22\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"12\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"27\" />\n" +
                "            <Equipe REF=\"1\" Score=\"0\" Statut=\"V\" Place=\"6\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"13\" >\n" +
                "            <Equipe REF=\"15\" Score=\"0\" Statut=\"V\" Place=\"7\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"26\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"14\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"23\" />\n" +
                "            <Equipe REF=\"10\" Score=\"0\" Statut=\"V\" Place=\"10\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"15\" >\n" +
                "            <Equipe REF=\"6\" Score=\"0\" Statut=\"V\" Place=\"15\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"18\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"16\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"31\" />\n" +
                "            <Equipe REF=\"13\" Score=\"0\" Statut=\"V\" Place=\"2\" />\n" +
                "          </Match>\n" +
                "        </Tableau>\n" +
                "      </SuiteDeTableaux>\n" +
                "      <SuiteDeTableaux ID=\"SuiteTab_B\" Titre=\"Tableau A\" NbDeTableaux=\"4\" DestinationDesQualifies=\"SuiteTab_E\" >\n" +
                "        <Tableau ID=\"B16\" Titre=\"Tableau A\" Taille=\"16\" DestinationDesElimines=\"SuiteTab_D\" >\n" +
                "          <Match ID=\"1\" >\n" +
                "            <Equipe REF=\"11\" Score=\"45\" Statut=\"V\" Place=\"1\" />\n" +
                "            <Equipe REF=\"5\" Score=\"13\" Statut=\"D\" Place=\"16\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"2\" >\n" +
                "            <Equipe REF=\"3\" Score=\"38\" Statut=\"D\" Place=\"9\" />\n" +
                "            <Equipe REF=\"4\" Score=\"45\" Statut=\"V\" Place=\"8\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"3\" >\n" +
                "            <Equipe REF=\"7\" Score=\"45\" Statut=\"V\" Place=\"5\" />\n" +
                "            <Equipe REF=\"16\" Score=\"20\" Statut=\"D\" Place=\"12\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"4\" >\n" +
                "            <Equipe REF=\"14\" Score=\"20\" Statut=\"D\" Place=\"13\" />\n" +
                "            <Equipe REF=\"2\" Score=\"45\" Statut=\"V\" Place=\"4\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"5\" >\n" +
                "            <Equipe REF=\"12\" Score=\"45\" Statut=\"V\" Place=\"3\" />\n" +
                "            <Equipe REF=\"9\" Score=\"41\" Statut=\"D\" Place=\"14\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"6\" >\n" +
                "            <Equipe REF=\"8\" Score=\"40\" Statut=\"D\" Place=\"11\" />\n" +
                "            <Equipe REF=\"1\" Score=\"45\" Statut=\"V\" Place=\"6\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"7\" >\n" +
                "            <Equipe REF=\"15\" Score=\"31\" Statut=\"D\" Place=\"7\" />\n" +
                "            <Equipe REF=\"10\" Score=\"45\" Statut=\"V\" Place=\"10\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"8\" >\n" +
                "            <Equipe REF=\"6\" Score=\"36\" Statut=\"D\" Place=\"15\" />\n" +
                "            <Equipe REF=\"13\" Score=\"45\" Statut=\"V\" Place=\"2\" />\n" +
                "          </Match>\n" +
                "        </Tableau>\n" +
                "        <Tableau ID=\"B8\" Titre=\"Tableau A\" Taille=\"8\" >\n" +
                "          <Match ID=\"1\" >\n" +
                "            <Equipe REF=\"11\" Score=\"45\" Statut=\"V\" Place=\"1\" />\n" +
                "            <Equipe REF=\"4\" Score=\"29\" Statut=\"D\" Place=\"8\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"2\" >\n" +
                "            <Equipe REF=\"7\" Score=\"35\" Statut=\"D\" Place=\"5\" />\n" +
                "            <Equipe REF=\"2\" Score=\"45\" Statut=\"V\" Place=\"4\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"3\" >\n" +
                "            <Equipe REF=\"12\" Score=\"43\" Statut=\"D\" Place=\"3\" />\n" +
                "            <Equipe REF=\"1\" Score=\"45\" Statut=\"V\" Place=\"6\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"4\" >\n" +
                "            <Equipe REF=\"10\" Score=\"39\" Statut=\"D\" Place=\"7\" />\n" +
                "            <Equipe REF=\"13\" Score=\"45\" Statut=\"V\" Place=\"2\" />\n" +
                "          </Match>\n" +
                "        </Tableau>\n" +
                "        <Tableau ID=\"B4\" Titre=\"Demi-finales\" Taille=\"4\" >\n" +
                "          <Match ID=\"1\" >\n" +
                "            <Equipe REF=\"11\" Score=\"43\" Statut=\"D\" Place=\"1\" />\n" +
                "            <Equipe REF=\"2\" Score=\"45\" Statut=\"V\" Place=\"4\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"2\" >\n" +
                "            <Equipe REF=\"1\" Score=\"45\" Statut=\"V\" Place=\"3\" />\n" +
                "            <Equipe REF=\"13\" Score=\"44\" Statut=\"D\" Place=\"2\" />\n" +
                "          </Match>\n" +
                "        </Tableau>\n" +
                "        <Tableau ID=\"B2\" Titre=\"Finale\" Taille=\"2\" >\n" +
                "          <Match ID=\"1\" >\n" +
                "            <Equipe REF=\"2\" Score=\"44\" Statut=\"D\" Place=\"1\" />\n" +
                "            <Equipe REF=\"1\" Score=\"45\" Statut=\"V\" Place=\"2\" />\n" +
                "          </Match>\n" +
                "        </Tableau>\n" +
                "      </SuiteDeTableaux>\n" +
                "      <SuiteDeTableaux ID=\"SuiteTab_c\" Titre=\"Tableau B\" NbDeTableaux=\"1\" DestinationDesQualifies=\"SuiteTab_D\" >\n" +
                "        <Tableau ID=\"C16\" Titre=\"Tableau B\" Taille=\"16\" >\n" +
                "          <Match ID=\"1\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"1\" />\n" +
                "            <Equipe REF=\"17\" Score=\"0\" Statut=\"V\" Place=\"16\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"2\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"V\" Place=\"9\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"V\" Place=\"8\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"3\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"V\" Place=\"5\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"V\" Place=\"12\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"4\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"V\" Place=\"13\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"V\" Place=\"4\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"5\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"V\" Place=\"3\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"V\" Place=\"14\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"6\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"V\" Place=\"11\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"V\" Place=\"6\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"7\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"V\" Place=\"7\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"V\" Place=\"10\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"8\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"V\" Place=\"15\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"V\" Place=\"2\" />\n" +
                "          </Match>\n" +
                "        </Tableau>\n" +
                "      </SuiteDeTableaux>\n" +
                "      <SuiteDeTableaux ID=\"SuiteTab_D\" Titre=\"Tableaux Division 2\" NbDeTableaux=\"4\" >\n" +
                "        <Tableau ID=\"D16\" Titre=\"Tableau D2 de 16\" Taille=\"16\" >\n" +
                "          <Match ID=\"1\" >\n" +
                "            <Equipe REF=\"15\" Score=\"0\" Statut=\"V\" Place=\"1\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"16\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"2\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"9\" />\n" +
                "            <Equipe REF=\"5\" Score=\"0\" Statut=\"V\" Place=\"8\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"3\" >\n" +
                "            <Equipe REF=\"14\" Score=\"0\" Statut=\"V\" Place=\"5\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"12\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"4\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"13\" />\n" +
                "            <Equipe REF=\"16\" Score=\"0\" Statut=\"V\" Place=\"4\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"5\" >\n" +
                "            <Equipe REF=\"8\" Score=\"0\" Statut=\"V\" Place=\"3\" />\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"14\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"6\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"11\" />\n" +
                "            <Equipe REF=\"9\" Score=\"0\" Statut=\"V\" Place=\"6\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"7\" >\n" +
                "            <Equipe REF=\"6\" Score=\"45\" Statut=\"V\" Place=\"7\" />\n" +
                "            <Equipe REF=\"17\" Score=\"31\" Statut=\"D\" Place=\"10\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"8\" >\n" +
                "            <Equipe REF=\"0\" Score=\"0\" Statut=\"D\" Place=\"15\" />\n" +
                "            <Equipe REF=\"3\" Score=\"0\" Statut=\"V\" Place=\"2\" />\n" +
                "          </Match>\n" +
                "        </Tableau>\n" +
                "        <Tableau ID=\"D8\" Titre=\"Tableau D2 de 8\" Taille=\"8\" >\n" +
                "          <Match ID=\"1\" >\n" +
                "            <Equipe REF=\"15\" Score=\"45\" Statut=\"V\" Place=\"1\" />\n" +
                "            <Equipe REF=\"5\" Score=\"13\" Statut=\"D\" Place=\"8\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"2\" >\n" +
                "            <Equipe REF=\"14\" Score=\"43\" Statut=\"D\" Place=\"5\" />\n" +
                "            <Equipe REF=\"16\" Score=\"45\" Statut=\"V\" Place=\"4\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"3\" >\n" +
                "            <Equipe REF=\"8\" Score=\"45\" Statut=\"V\" Place=\"3\" />\n" +
                "            <Equipe REF=\"9\" Score=\"40\" Statut=\"D\" Place=\"6\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"4\" >\n" +
                "            <Equipe REF=\"6\" Score=\"25\" Statut=\"D\" Place=\"7\" />\n" +
                "            <Equipe REF=\"3\" Score=\"45\" Statut=\"V\" Place=\"2\" />\n" +
                "          </Match>\n" +
                "        </Tableau>\n" +
                "        <Tableau ID=\"D4\" Titre=\"Tableau D2 de 4\" Taille=\"4\" >\n" +
                "          <Match ID=\"1\" >\n" +
                "            <Equipe REF=\"15\" Score=\"45\" Statut=\"V\" Place=\"1\" />\n" +
                "            <Equipe REF=\"16\" Score=\"30\" Statut=\"D\" Place=\"4\" />\n" +
                "          </Match>\n" +
                "          <Match ID=\"2\" >\n" +
                "            <Equipe REF=\"8\" Score=\"45\" Statut=\"V\" Place=\"3\" />\n" +
                "            <Equipe REF=\"3\" Score=\"36\" Statut=\"D\" Place=\"2\" />\n" +
                "          </Match>\n" +
                "        </Tableau>\n" +
                "        <Tableau ID=\"D2\" Titre=\"9e place\" Taille=\"2\" >\n" +
                "          <Match ID=\"1\" >\n" +
                "            <Equipe REF=\"15\" Score=\"45\" Statut=\"V\" Place=\"1\" />\n" +
                "            <Equipe REF=\"8\" Score=\"35\" Statut=\"D\" Place=\"2\" />\n" +
                "          </Match>\n" +
                "        </Tableau>\n" +
                "      </SuiteDeTableaux>\n" +
                "      <SuiteDeTableaux ID=\"SuiteTab_E\" Titre=\"Tableaux Division 1\" NbDeTableaux=\"0\" >\n" +
                "      </SuiteDeTableaux>\n" +
                "    </PhaseDeTableaux>\n" +
                "  </Phases>\n" +
                "</CompetitionParEquipes>\n";

        return getFakeFile(faxeXML);
    }


    public File threeFencersIndivualCompetition() throws IOException {

        final String faxeXML = "<?xml version=\"1.0\" encoding=\"iso-8859-1\" ?>\n" +
                "<!DOCTYPE CompetitionIndividuelle>\n" +
                "<CompetitionIndividuelle Championnat=\"Circuit\" Annee=\"2006\" Arme=\"S\" Sexe=\"M\" Domaine=\"N\" Federation=\"FFE\" Organisateur=\"SUC\" Categorie=\"S\" Date=\"12.02.2006\" TitreCourt=\"SHS CN Strasbourg\" TitreLong=\"SHS Circuit National Strasbourg\" >\n" +
                "  <Tireurs>\n" +
                "    <Tireur ID=\"76\" Nom=\"AGRESTA\" Prenom=\"Renzo\" DateNaissance=\"00.00.1985\" Sexe=\"M\" Nation=\"BRA\" Club=\"BRAZIL\" Classement=\"12\" Statut=\"N\" />\n" +
                "    <Tireur ID=\"2\" Nom=\"ANSTETT\" Prenom=\"Vincent\" DateNaissance=\"26.07.1982\" Sexe=\"M\" Nation=\"FRA\" Ligue=\"ALSACE\" Club=\"STRASBOUR UC\" Classement=\"19\" Statut=\"N\" />\n" +
                "    <Tireur ID=\"13\" Nom=\"APITHY\" Prenom=\"Bolade\" DateNaissance=\"21.08.1985\" Sexe=\"M\" Nation=\"FRA\" Ligue=\"BOURGOGNE\" Club=\"DIJON ASPTT\" Classement=\"8\" Statut=\"N\" />\n" +
                "</Tireurs>\n" +
                "</CompetitionIndividuelle>\n";

        return getFakeFile(faxeXML);

    }
}
